AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AmazonConnectSample

Parameters:
  DestinationPhoneNumber:
    Type: String
  SourcePhoneNumber:
    Type: String
  InstanceId:
    Type: String
  ContactFlowId:
    Type: String

Globals:
  Function:
    Timeout: 10

Resources:
  PhonePublishFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: phone-publish-function
      CodeUri: src/publish
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          DESTINATION_PHONE_NUMBER:
            Ref: DestinationPhoneNumber
          SOURCE_PHONE_NUMBER:
            Ref: SourcePhoneNumber
          INSTANCE_ID:
            Ref: InstanceId
          CONTACT_FLOW_ID:
            Ref: ContactFlowId
      Role: !GetAtt PhonePublishFunctionRole.Arn

  PhonePublishFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: phone-publish-function-role
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
              - Effect: Allow
                Action:
                  - connect:StartOutboundVoiceContact
                  - connect:StopContact
                Resource: '*'

  PhoneSubscribeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: phone-subscribe-function
      CodeUri: src/subscribe
      Handler: app.lambda_handler
      Runtime: python3.7
